<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKnxaadj\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKnxaadj/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKnxaadj.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKnxaadj\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKnxaadj\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Knxaadj',
    'container.build_id' => 'ead0a373',
    'container.build_time' => 1527236402,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKnxaadj');
